[package]
name = "ite-keyboard"
version = "0.1.0"
authors = ["Fabio De Santi <fsanti68@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.2.2"
lazy_static = "1.4.0"